### ISSUE TITLE
Store keys in keystore rather than just setting system properties

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas_course_manager#254]
We had this issue come up with the security key recently.

It might be better if we actually added the key to the local keystore (at runtime) rather than adding these as System properties. Something with that caused this process to no longer work.

https://stackoverflow.com/questions/3027273/how-to-store-and-load-keys-using-java-security-keystore-class

Some code around this may want to catch the javax.net.ssl.SSLHandshakeException specifically and do something in this case.

**Comment by jonespm** [comment]
This code that uses this is part of the Friend service and may be removed when social login is implemented in spring 2020

**Comment by jonespm** [comment]
I believe the social login code was removed so this shouldn't cause a problem. Re-open if this is still an issue.

**Comment by pushyamig** [comment]
SOCIAL login is not using keystore anymore. So we don't need to look back. But all the code for friend account code remain there we did not remove it yet since not worth the time since we are going with rewrite of this app
