### ISSUE TITLE
SSLCiphers & SSLProtocol improvements

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas_course_manager#269]
Remove protocols < TLSv1.2, and only use strong ciphers for TLSv1.2 and TLSv1.3.

**Comment by pushyamig** [comment]
@jonespm Sorry I have Assigned to you by mistake

**Comment by cousinea** [comment]
Specifically changed apache configuration to:

SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1

to match "Intermediate" compatibility per:

https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by pushyamig** [comment]
Test: 
Testing this going to https://www.ssllabs.com/ssltest/analyze.html?d=ccmqa.tl.it.umich.edu&s=3.17.44.98&hideResults=on&latest and looking at the Cipher suites and Protocols
New: 
![Screen Shot 2019-11-14 at 10 17 29 AM](https://user-images.githubusercontent.com/8579775/71095366-7a4fd380-217a-11ea-8d98-9e52fbdde8aa.png)
Old:
![Screen Shot 2019-11-14 at 10 18 13 AM](https://user-images.githubusercontent.com/8579775/71095379-7e7bf100-217a-11ea-899e-c28a2727d3b0.png)

**Comment by pushyamig** [comment]
Test passed in QA
